"""add PostRating.last_vote

Revision ID: 304fbd6a7e5f
Revises: 74c3910ff3dd
Create Date: 2021-03-24 23:46:36.152091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304fbd6a7e5f'
down_revision = '74c3910ff3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_vote', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts_rating', schema=None) as batch_op:
        batch_op.drop_column('last_vote')

    # ### end Alembic commands ###
