"""empty message

Revision ID: 5823d77867a0
Revises: fb2ab322e6de
Create Date: 2021-03-25 03:02:15.128647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5823d77867a0'
down_revision = 'fb2ab322e6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts_rating', schema=None) as batch_op:
        batch_op.drop_column('last_vote')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_vote', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
